/**
 * @fileoverview gRPC-Web generated client stub for protoblog
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.6
// source: v_registry_server.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.protoblog = require('./v_registry_server_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.protoblog.VRegistryServerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.protoblog.VRegistryServerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.protoblog.RegistryRequest,
 *   !proto.protoblog.StringListReply>}
 */
const methodDescriptor_VRegistryServer_GetDbNames = new grpc.web.MethodDescriptor(
  '/protoblog.VRegistryServer/GetDbNames',
  grpc.web.MethodType.UNARY,
  proto.protoblog.RegistryRequest,
  proto.protoblog.StringListReply,
  /**
   * @param {!proto.protoblog.RegistryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.protoblog.StringListReply.deserializeBinary
);


/**
 * @param {!proto.protoblog.RegistryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.protoblog.StringListReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.protoblog.StringListReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.protoblog.VRegistryServerClient.prototype.getDbNames =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/protoblog.VRegistryServer/GetDbNames',
      request,
      metadata || {},
      methodDescriptor_VRegistryServer_GetDbNames,
      callback);
};


/**
 * @param {!proto.protoblog.RegistryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.protoblog.StringListReply>}
 *     Promise that resolves to the response
 */
proto.protoblog.VRegistryServerPromiseClient.prototype.getDbNames =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/protoblog.VRegistryServer/GetDbNames',
      request,
      metadata || {},
      methodDescriptor_VRegistryServer_GetDbNames);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.protoblog.RegistryRequest,
 *   !proto.protoblog.StringListReply>}
 */
const methodDescriptor_VRegistryServer_GetCollNames = new grpc.web.MethodDescriptor(
  '/protoblog.VRegistryServer/GetCollNames',
  grpc.web.MethodType.UNARY,
  proto.protoblog.RegistryRequest,
  proto.protoblog.StringListReply,
  /**
   * @param {!proto.protoblog.RegistryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.protoblog.StringListReply.deserializeBinary
);


/**
 * @param {!proto.protoblog.RegistryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.protoblog.StringListReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.protoblog.StringListReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.protoblog.VRegistryServerClient.prototype.getCollNames =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/protoblog.VRegistryServer/GetCollNames',
      request,
      metadata || {},
      methodDescriptor_VRegistryServer_GetCollNames,
      callback);
};


/**
 * @param {!proto.protoblog.RegistryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.protoblog.StringListReply>}
 *     Promise that resolves to the response
 */
proto.protoblog.VRegistryServerPromiseClient.prototype.getCollNames =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/protoblog.VRegistryServer/GetCollNames',
      request,
      metadata || {},
      methodDescriptor_VRegistryServer_GetCollNames);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.protoblog.RegistryRequest,
 *   !proto.protoblog.StringReply>}
 */
const methodDescriptor_VRegistryServer_SwitchUser = new grpc.web.MethodDescriptor(
  '/protoblog.VRegistryServer/SwitchUser',
  grpc.web.MethodType.UNARY,
  proto.protoblog.RegistryRequest,
  proto.protoblog.StringReply,
  /**
   * @param {!proto.protoblog.RegistryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.protoblog.StringReply.deserializeBinary
);


/**
 * @param {!proto.protoblog.RegistryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.protoblog.StringReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.protoblog.StringReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.protoblog.VRegistryServerClient.prototype.switchUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/protoblog.VRegistryServer/SwitchUser',
      request,
      metadata || {},
      methodDescriptor_VRegistryServer_SwitchUser,
      callback);
};


/**
 * @param {!proto.protoblog.RegistryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.protoblog.StringReply>}
 *     Promise that resolves to the response
 */
proto.protoblog.VRegistryServerPromiseClient.prototype.switchUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/protoblog.VRegistryServer/SwitchUser',
      request,
      metadata || {},
      methodDescriptor_VRegistryServer_SwitchUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.protoblog.RegistryRequest,
 *   !proto.protoblog.LsReply>}
 */
const methodDescriptor_VRegistryServer_Ls = new grpc.web.MethodDescriptor(
  '/protoblog.VRegistryServer/Ls',
  grpc.web.MethodType.UNARY,
  proto.protoblog.RegistryRequest,
  proto.protoblog.LsReply,
  /**
   * @param {!proto.protoblog.RegistryRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.protoblog.LsReply.deserializeBinary
);


/**
 * @param {!proto.protoblog.RegistryRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.protoblog.LsReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.protoblog.LsReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.protoblog.VRegistryServerClient.prototype.ls =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/protoblog.VRegistryServer/Ls',
      request,
      metadata || {},
      methodDescriptor_VRegistryServer_Ls,
      callback);
};


/**
 * @param {!proto.protoblog.RegistryRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.protoblog.LsReply>}
 *     Promise that resolves to the response
 */
proto.protoblog.VRegistryServerPromiseClient.prototype.ls =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/protoblog.VRegistryServer/Ls',
      request,
      metadata || {},
      methodDescriptor_VRegistryServer_Ls);
};


module.exports = proto.protoblog;

